# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chartWidget',
        ),
    ]
