---
- hosts: database_mongoDB
  remote_user: ubuntu
  sudo: yes
  tasks:
  
  - name: update system packages
    action:
      module: apt
      update_cache: yes
      cache_valid_time: 3600
      upgrade: dist
      force: yes

  - name: Add mongo ppa key
    sudo: yes
    apt_key: >
      keyserver=hkp://keyserver.ubuntu.com:80
      id=7F0CEB10
      state=present

  - name: Add mongo sources list
    sudo: yes
    lineinfile: >
      line="deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse"
      dest=/etc/apt/sources.list.d/mongodb.list
      state=present
      create=yes

  - name: Install mongo
    sudo: yes
    apt: 
      name: mongodb-org 
      state: latest 
      update_cache: yes
      force: yes 

  - name: install ntp
    action:
      module: apt
      package: ntp
      state: present
    
  - name: install https apt transport
    apt: name=apt-transport-https state=present

  - name: Add dataloop gpg key
    apt_key: id=113E2B8D url='https://download.dataloop.io/pubkey.gpg' state=present

  - name: Add dataloop apt repository
    apt_repository: repo='deb https://download.dataloop.io/deb/ stable main' state=present

  - name: Install dataloop
    apt: name=dataloop-agent state=present

  - name: Copy Outlyer config file
    template: src=../templates/outlyer/mongo/agent.yaml dest=/etc/dataloop/agent.yaml owner=root group=dataloop mode=640
    notify: restart dataloop-agent

  - service:
      name: dataloop-agent
      state: stopped

  - service:
      name: dataloop-agent
      state: started
