---
- hosts: mqtt_kafka_adapter
  remote_user: ubuntu
  sudo: yes
  vars:
    packages:
      - supervisor
  tasks:
  - name: update system packages
    action:
      module: apt
      update_cache: yes
      cache_valid_time: 3600
      upgrade: dist
      force: yes

  - name : install  packages
    action:
      module : apt
      update_cache: yes
     # name : "{{ item }}"
      name: supervisor
      state: present
      force: yes
   # with_items : packages

  - name: Copy supervisor config file
    action:
      module: copy
      src: ../templates/supervisor/supervisord.conf
      dest: /etc/supervisor/supervisord.conf
      owner: root
      group: root
      mode: 0644

  - name: Restart supervisor service
    action:
     module: service
     name: supervisor
     state: restarted

  - name: Copy mqtt_kafka_adapter binary file
    synchronize: src=../../mqtt_to_kafka.jar  dest=/home/ubuntu/
    with_items:
      - "kafka"

  - name: Install add-apt-repostory
    become: yes
    apt: name=software-properties-common state=latest

  - name: Add Oracle Java Repository
    become: yes
    apt_repository: repo='ppa:webupd8team/java'

  - name: dpkg configure, must be here, otherwise java can not be installed
    become: yes
    shell: dpkg --configure -a

  - name: Accept Java 8 License
    become: yes
    debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

  - name: Install Oracle Java 8
    become: yes
    apt: name={{item}} state=latest
    with_items:
      - oracle-java8-installer
      - oracle-java8-set-default

  - name: start mqtt_to_kafka
    become: yes
    shell: supervisorctl start mqtt_kafka_adapter
