---
- hosts: zookeeper
  remote_user: ubuntu
  sudo: true
  vars:
    zookeeper_path: kafka/kafka_2.11-0.11.0.0
  tasks:

  - name: update system packages
    action:
      module: apt
      update_cache: yes
      cache_valid_time: 3600
      upgrade: dist
      force: yes

  - name : install  packages
    action:
      module : apt
      update_cache: yes
     # name : "{{ item }}"
      name: supervisor
      state: present
      force: yes
   # with_items : packages

  - name: Copy supervisor config file
    action:
      module: copy
      src: ../templates/supervisor/supervisord.conf
      dest: /etc/supervisor/supervisord.conf
      owner: root
      group: root
      mode: 0644

  - name: Restart supervisor service
    action:
      module: service
      name: supervisor
      state: started
    #ignore_errors: true

  - name: Copy kafka folder
    synchronize: src=../{{item}}  dest=/home/ubuntu/
    with_items:
      - "kafka"

  - name: Install add-apt-repostory
    become: yes
    apt: name=software-properties-common state=latest

  - name: Add Oracle Java Repository
    become: yes
    apt_repository: repo='ppa:webupd8team/java'

  - name: dpkg configure, must be here, otherwise java can not be installed
    become: yes
    shell: dpkg --configure -a

  - name: Accept Java 8 License
    become: yes
    debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

  - name: Install Oracle Java 8
    become: yes
    apt: name={{item}} state=latest
    with_items:
      - oracle-java8-installer
      - oracle-java8-set-default

  - name: start zookeeper
    become: yes
    shell: supervisorctl start zookeeper

  - name : install git package
    action:
      module : apt
      update_cache: yes
      name: git
      state: present
      force: yes
  
  - name: clone LinkedIn Burrow repository 
    git:
      repo: https://github.com/linkedin/Burrow.git
      dest: /home/ubuntu/burrow/
      clone: yes
 
  - name: create /etc/burrow/ directory
    file: 
       path: /etc/burrow/ 
       mode: 0755 
       state: directory

  - name: create /var/log/burrow/ directory
    file: 
       path: /var/log/burrow/ 
       mode: 0755 
       state: directory
  
  - name: Copy burrow config file
    action:
      module: copy
      src: ../templates/burrow/burrow.cfg
      dest: /etc/burrow/burrow.cfg
      owner: root
      group: root
      mode: 0644 
 
  - name: Copy burrow logging config file
    action:
      module: copy
      src: ../templates/burrow/logging.cfg
      dest: /etc/burrow/logging.cfg
      owner: root
      group: root
      mode: 0644 
  
  - name: ensure repository key is installed
    apt_key:
      id: "58118E89F3A912897C070ADBF76221572C52609D"
      keyserver: "hkp://p80.pool.sks-keyservers.net:80"
      state: present

  - name: ensure docker registry is available
    # For Ubuntu 14.04 LTS, use this repository:
    apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present

  - name: ensure docker and dependencies are installed
    apt: name=docker-engine update_cache=yes

  - service: name=docker state=restarted

  - name: pull burrow docker image
    command: 'docker pull magnetme/burrow' 

  - name: run burrow docker container
    command: "docker run  -d -v /etc/burrow:/etc/burrow -p 8000:8000 magnetme/burrow"

  - name : install  packages
    action:
      module : apt
      update_cache: yes
      name: jq 
      state: present
      force: yes

  - name: Copy monitoring/kafka_total_lag.sh 
    action:
      module: copy
      src: ../monitoring/kafka_total_lag.sh
      dest: /opt/kafka_total_lag.sh
      owner: root
      group: root
      mode: 0755
 
  - name: reread supervisor config file
    become: yes
    shell: supervisorctl reread
 
  - name: start monitoring/kafka_total_lag.sh
    become: yes
    shell: supervisorctl start kafka-total-lag-monitoring
