---
- hosts: mqtt_kafka_adapter
  remote_user: ubuntu
  sudo: true
  vars: 
    kafka_client_path: kafka/kafka_2.11-0.11.0.0
  tasks:

  - name: Copy kafka folder
    synchronize: src=../{{item}}  dest=/home/ubuntu/
    with_items:
      - "kafka"

  - name: Install add-apt-repostory
    become: yes
    apt: name=software-properties-common state=latest

  - name: Add Oracle Java Repository
    become: yes
    apt_repository: repo='ppa:webupd8team/java'

  - name: dpkg configure, must be here, otherwise java can not be installed
    become: yes
    shell: dpkg --configure -a

  - name: Accept Java 8 License
    become: yes
    debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

  - name: Install Oracle Java 8
    become: yes
    apt: name={{item}} state=latest
    with_items:
      - oracle-java8-installer
      - oracle-java8-set-default

#  - name: Run Zookeeper - fire and forget
#    become: yes
#    shell: "{{kafka_client_path}}/bin/zookeeper-server-start.sh {{kafka_client_path}}/config/zookeeper.properties"
#    async: 10
#    poll: 0
