---
- hosts: workload_clients
  remote_user: ubuntu
  sudo: true
  tasks:
   
  - file:
      path: /home/ubuntu/workload_generation   
      state: directory
      mode: 0755

  - name: copy files
    copy:
      src: "../workload_generation/{{ item }}" 
      dest: "/home/ubuntu/workload_generation"
      mode: 0777
    with_items:
    - "client_publish_message.sh"
    - "run_clients.sh"
    - "dataSet.csv"

  - name: install mosquito client 
    apt: name=mosquitto-clients update_cache=yes

  - name: install ntp
    action:
      module: apt
      package: ntp
      state: present

  - name: install https apt transport
    apt: name=apt-transport-https state=present

  - name: Add dataloop gpg key
    apt_key: id=113E2B8D url='https://download.dataloop.io/pubkey.gpg' state=present

  - name: Add dataloop apt repository
    apt_repository: repo='deb https://download.dataloop.io/deb/ stable main' state=present

  - name: Install dataloop
    apt: name=dataloop-agent state=present

  - name: Copy Outlyer config file
    template: src=../templates/outlyer/mqtt_client/agent.yaml dest=/etc/dataloop/agent.yaml owner=root group=dataloop mode=640
    notify: restart dataloop-agent

  - service:
      name: dataloop-agent
      state: restarted
